### ISSUE TITLE
[EN] Translate readme to English

### ISSUE THREAD

**Issue by Ahelsamahy** [TheBSD/poykott-old#15]
If there is a way for the repo to reach a broader audience, then there is a need to translate it to English. I can help with this one.

To Do list
- [ ]  Translate readme.md to English
- [ ]  Add section for languages in it

**Comment by TheBSD** [comment]
Go Ahead!

translation is very good for the project.

just add another readme.en.md

and we will add languages for the content

**Comment by pizofreude** [comment]
How the progress on this translation? Otherwise I'll fill in and help with the README-EN.md translation.

**Comment by sukalaper** [comment]
Is there a continuation of this assignment?

**Comment by TheBSD** [comment]
@sukalaper 

Yes. I am waiting for english translation 

I was busy lately so I didn't update so much..

**Comment by Ahelsamahy** [comment]
This issue has been addressed at https://github.com/TheBSD/poykott/pull/22 . I will close it here, then.
